spring:
  application:
    name: controlHQ
  config:
    import:
      - optional:file:.env[.properties]
      - configtree:/run/secrets/
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{transactionId}] - %msg%n"
app:
  jwt:
    secret: ${jwt_secret}