spring:
  application:
    name: controlHQ
  config:
    import: optional:file:.env[.properties]
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{transactionId}] - %msg%n"